### ISSUE TITLE
[BUG]: 首次运行插件时，所有功能都不可用（定时任务执行的延时问题）

### ISSUE THREAD

**Issue by Ikaros-521** [A-kirami/nonebot-plugin-exchangerate#1]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [ ] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

### 影响版本

0.1.0

### 问题描述

fetch_exchange的缺个首次运行调用
```
@scheduler.scheduled_job(
    "interval", minutes=30, args=[config.exchange_app_key], next_run_time=datetime.now()
)
async def fetch_exchange(app_key: str) -> None:
```

### 复现步骤

直接运行就复现

### 额外补充

直接换算的正则范围太宽了，一输入数字就拉去换算了，有点影响正常聊天。建议加上 前后缀等触发词

**Comment by A-kirami** [comment]
没有理解你的问题，目前 `fetch_exchange` 在 nb2 启动之后就会立即执行一次拉取汇率信息

**Comment by Ikaros-521** [comment]
> 没有理解你的问题，目前 `fetch_exchange` 在 nb2 启动之后就会立即执行一次拉取汇率信息

就是没有立即拉0.0

**Comment by A-kirami** [comment]
> > 没有理解你的问题，目前 `fetch_exchange` 在 nb2 启动之后就会立即执行一次拉取汇率信息
> 
> 就是没有立即拉0.0

啊这？这在本地测试是正常的，你可以尝试只加载这一个插件看看，或许与其他插件的定时任务冲突
![image](https://user-images.githubusercontent.com/66513481/206856228-403bb0dc-ffa7-4d14-a893-3d78d97b4aa3.png)

**Comment by Ikaros-521** [comment]
> > > 没有理解你的问题，目前 `fetch_exchange` 在 nb2 启动之后就会立即执行一次拉取汇率信息
> > 
> > 
> > 就是没有立即拉0.0
> 
> 啊这？这在本地测试是正常的，你可以尝试只加载这一个插件看看，或许与其他插件的定时任务冲突 ![image](https://user-images.githubusercontent.com/66513481/206856228-403bb0dc-ffa7-4d14-a893-3d78d97b4aa3.png)

![)DUBG(6{KOM 5)IPEUH_K22](https://user-images.githubusercontent.com/40910637/206856645-1e027cef-c62c-415e-839d-75db691d9c56.png)
![R@$P1FBN2LFH (3 L3(J0DN](https://user-images.githubusercontent.com/40910637/206856658-9d0c7752-e121-4d8d-ad5c-60b2973a0da7.png)
`next_run_time=datetime.datetime.now() + datetime.timedelta(hours=0, minutes=0, seconds=10)`
定时任务的运行晚于插件加载吧

**Comment by A-kirami** [comment]
顺便，只有数字的话应该是不会触发的
![image](https://user-images.githubusercontent.com/66513481/206857090-362b249c-e30f-4111-8418-2a6b5d430d7f.png)

**Comment by Ikaros-521** [comment]
> 顺便，只有数字的话应该是不会触发的 ![image](https://user-images.githubusercontent.com/66513481/206857090-362b249c-e30f-4111-8418-2a6b5d430d7f.png)

恩 但是200天 这种会触发

**Comment by A-kirami** [comment]
已发布新版，请检查是否修复问题

**Comment by Ikaros-521** [comment]
> 已发布新版，请检查是否修复问题

可以了✌️
